package com.banking.gateway.controller;

import com.banking.common.domain.ApiResponse;
import com.banking.gateway.service.BankingAiService;
import jakarta.validation.constraints.NotBlank;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

/**
 * AI-powered banking assistant endpoints.
 * All responses are generated by GPT-4o using real banking data via MCP tools.
 */
@Validated
@RestController
@RequestMapping("/api/v1/banking-ai")
@RequiredArgsConstructor
public class BankingAiController {

    private final BankingAiService bankingAiService;

    /**
     * POST /api/v1/banking-ai/chat
     * Multi-turn conversation with full MCP tool access.
     *
     * Example prompts:
     *  "Onboard a new customer Alice Johnson, DOB 1990-05-15, email alice@example.com..."
     *  "Check the balance of account ACC-001"
     *  "Send $5000 from ACC-001 to ACC-002 via IMPS, run fraud check and process if safe"
     *  "Show me all pending KYC customers"
     */
    @PostMapping("/chat")
    public ResponseEntity<ApiResponse<Map<String, Object>>> chat(
            @RequestBody Map<String, String> body) {
        String sessionId = body.getOrDefault("sessionId", "default");
        String message   = body.get("message");

        if (message == null || message.isBlank()) {
            return ResponseEntity.badRequest()
                    .body(ApiResponse.failure("'message' field is required", "INVALID_REQUEST"));
        }

        String response = bankingAiService.chat(sessionId, message);
        return ResponseEntity.ok(ApiResponse.success(Map.of(
            "sessionId", sessionId,
            "response",  response
        )));
    }

    /**
     * POST /api/v1/banking-ai/query
     * Single-turn stateless query — no history maintained.
     */
    @PostMapping("/query")
    public ResponseEntity<ApiResponse<String>> query(
            @RequestBody Map<String, String> body) {
        String message  = body.get("message");
        String response = bankingAiService.singleQuery(message);
        return ResponseEntity.ok(ApiResponse.success(response));
    }

    /** GET /api/v1/banking-ai/sessions/{sessionId}/history */
    @GetMapping("/sessions/{sessionId}/history")
    public ResponseEntity<ApiResponse<List<Map<String, String>>>> getHistory(
            @PathVariable @NotBlank String sessionId) {
        return ResponseEntity.ok(ApiResponse.success(bankingAiService.getSessionHistory(sessionId)));
    }

    /** DELETE /api/v1/banking-ai/sessions/{sessionId} */
    @DeleteMapping("/sessions/{sessionId}")
    public ResponseEntity<ApiResponse<String>> clearSession(
            @PathVariable String sessionId) {
        bankingAiService.clearSession(sessionId);
        return ResponseEntity.ok(ApiResponse.success("Session cleared: " + sessionId));
    }

    /** GET /api/v1/banking-ai/sessions */
    @GetMapping("/sessions")
    public ResponseEntity<ApiResponse<Map<String, Object>>> getSessionStats() {
        return ResponseEntity.ok(ApiResponse.success(bankingAiService.getSessionStats()));
    }
}
